#!/bin/bash
set +e
INSTALL_DIR='~/.devbox-setup-ubuntu'
GIT_REPO=''

mkpir -p "$INSTALL_DIR"
git clone "$GIT_REPO" "$INSTALL_DIR"
cd "$INSTALL_DIR"
echo "Now cd \"$INSTALL_DIR\" and call needed installers from $INSTALL_DIR/bin"
